import { HistoryEntry } from '../DiscoverPage';

// ─── Mock data ────────────────────────────────────────────────────────────────
export const VIDEOS_DATA: HistoryEntry[] = [
  { id: 1001, platform: 'YouTube',    duration: '14:32', date: 'Mar 8, 2026',  words: 3820, title: 'How I Built a $10M SaaS in 12 Months',        creator: '@tokcast',        thumbnail: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&q=80',  transcriptSnippet: "I want to talk about the exact playbook we used to grow from zero to $10M ARR without a single enterprise sales rep. It starts with ruthless focus..." },
  { id: 1002, platform: 'TikTok',     duration: '0:58', date: 'Mar 7, 2026',  words: 1420, title: '5 Morning Habits That Changed My Life',          creator: '@productivityhacks', thumbnail: 'https://images.unsplash.com/photo-1519125323398-675f0ddb6308?w=400&q=80', transcriptSnippet: "Good morning, everyone. I've been doing these five habits for 18 months straight and honestly my output has doubled. Let me break them down..." },
  { id: 1003, platform: 'Instagram',  duration: '1:23', date: 'Mar 6, 2026',  words: 2100, title: 'The Secret to Perfect Pasta Every Time',         creator: '@chefmike',          thumbnail: 'https://images.unsplash.com/photo-1555949258-eb67b1ef0ceb?w=400&q=80', transcriptSnippet: "Okay, today I'm settling this once and for all. The number one mistake people make when cooking pasta is not using enough salt in the water..." },
  { id: 1004, platform: 'YouTube',    duration: '22:10', date: 'Mar 5, 2026',  words: 6750, title: 'React Server Components Explained Simply',        creator: '@webdevdaily',       thumbnail: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=400&q=80', transcriptSnippet: "React Server Components fundamentally change how we think about data fetching. Instead of fetching on the client and showing loading states..." },
  { id: 1005, platform: 'LinkedIn',   duration: '4:47', date: 'Mar 4, 2026',  words: 1890, title: 'Why Most LinkedIn Posts Fail (And How to Fix It)', creator: '@growthops',         thumbnail: 'https://images.unsplash.com/photo-1560804624-8798f895c85f?w=400&q=80', transcriptSnippet: "I've analysed 1,200 LinkedIn posts this year. The pattern is clear — the ones that fail all share the same three mistakes. Let me show you..." },
  { id: 1006, platform: 'TikTok',     duration: '0:45', date: 'Mar 3, 2026',  words: 980,  title: '30-Day Fitness Challenge Results',                 creator: '@fitnesswithsarah',  thumbnail: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=400&q=80', transcriptSnippet: "Day 30. I cannot believe I actually made it. My starting weight was 182 pounds and today I stepped on the scale and saw..." },
  { id: 1007, platform: 'YouTube',    duration: '18:44', date: 'Mar 2, 2026',  words: 5420, title: 'Design Tokens: The Complete Workflow',             creator: '@designsystem',      thumbnail: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=400&q=80', transcriptSnippet: "Design tokens are the foundation of any scalable design system. But most teams implement them wrong. Today I'll walk you through the exact process..." },
  { id: 1008, platform: 'Instagram',  duration: '1:15', date: 'Mar 1, 2026',  words: 2340, title: 'Street Food Tour: Bangkok Night Market',           creator: '@roamingalex',       thumbnail: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&q=80', transcriptSnippet: "Welcome to the Chatuchak Weekend Market at night. This place transforms completely after dark. The aromas hit you before you even get through the entrance..." },
  { id: 1009, platform: 'Twitter/X',  duration: '3:22', date: 'Feb 28, 2026', words: 1650, title: 'The Indie Hacker Mindset Explained',               creator: '@buildinpublic',     thumbnail: 'https://images.unsplash.com/photo-1627667050609-d4ba6483a368?w=400&q=80', transcriptSnippet: "Being an indie hacker isn't just a business model. It's a completely different way of thinking about value, time, and leverage. Here's what I mean..." },
  { id: 1010, platform: 'YouTube',    duration: '28:14', date: 'Feb 27, 2026', words: 8900, title: 'Mastering Composition in Street Photography',       creator: '@lenspov',           thumbnail: 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?w=400&q=80', transcriptSnippet: "Composition is everything in street photography. The decisive moment only matters if you've already got a strong frame. Let me break down my process..." },
  { id: 1011, platform: 'TikTok',     duration: '0:52', date: 'Feb 25, 2026', words: 1120, title: 'How to Read 52 Books a Year',                      creator: '@booknerd',          thumbnail: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80', transcriptSnippet: "One book a week sounds impossible until you realise most people spend 3 hours a day on their phone. That's all the time you need..." },
  { id: 1012, platform: 'LinkedIn',   duration: '6:08', date: 'Feb 23, 2026', words: 2760, title: 'Building a Second Brain: My System After 2 Years',  creator: '@pkm_nerd',          thumbnail: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=400&q=80', transcriptSnippet: "Two years ago I started building a second brain. Today I want to share what actually stuck and what turned out to be a complete waste of time..." },
  { id: 1013, platform: 'YouTube',    duration: '11:33', date: 'Feb 22, 2026', words: 4100, title: 'Docker in 5 Minutes — No Fluff Guide',             creator: '@techguru',          thumbnail: 'https://images.unsplash.com/photo-1605745341112-85968b19335b?w=400&q=80', transcriptSnippet: "Docker doesn't need to be complicated. In this video I'm going to cut out all the theory and show you exactly what you need to containerise your app..." },
  { id: 1014, platform: 'Instagram',  duration: '2:05', date: 'Feb 20, 2026', words: 3450, title: 'What No One Tells You About Remote Work',           creator: '@remotefirst',       thumbnail: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&q=80', transcriptSnippet: "Everyone talks about the freedom of remote work. Nobody talks about the loneliness, the 'always on' pressure, or the promotion blindspot. Let me be honest..." },
  { id: 1015, platform: 'YouTube',    duration: '9:17', date: 'Feb 18, 2026', words: 3200, title: 'Perfect Sourdough Bread — Science-Based Recipe',    creator: '@kitchenlabs',       thumbnail: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80', transcriptSnippet: "Sourdough is just flour, water, salt, and wild yeast. But getting it right requires understanding a little chemistry. Here's the science behind a perfect loaf..." },
  { id: 1016, platform: 'TikTok',     duration: '1:09', date: 'Feb 15, 2026', words: 1580, title: 'Tokyo in 60 Seconds',                              creator: '@worldwanderer',     thumbnail: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=400&q=80', transcriptSnippet: "Tokyo is the most overwhelming and most wonderful city I have ever visited. In one minute I want to try and capture why it's unlike anywhere else..." },
];
